// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPPhGrKUnNRz_MWRv2mzi0aw2benRTyu8',
    appId: '1:35180612639:web:e6433204d9557b81bd592a',
    messagingSenderId: '35180612639',
    projectId: 'flutterrestapi-17c56',
    authDomain: 'flutterrestapi-17c56.firebaseapp.com',
    storageBucket: 'flutterrestapi-17c56.appspot.com',
    measurementId: 'G-CJ1063VMCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRgq1tXbz4qBQ5m-JjnXDY-a9md8c9VJs',
    appId: '1:35180612639:android:add8049f49ae592cbd592a',
    messagingSenderId: '35180612639',
    projectId: 'flutterrestapi-17c56',
    storageBucket: 'flutterrestapi-17c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNnjpUYZ0s6v_V6CGwWc2czCFOf_7dCwA',
    appId: '1:35180612639:ios:981a70a42dfd9687bd592a',
    messagingSenderId: '35180612639',
    projectId: 'flutterrestapi-17c56',
    storageBucket: 'flutterrestapi-17c56.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNnjpUYZ0s6v_V6CGwWc2czCFOf_7dCwA',
    appId: '1:35180612639:ios:981a70a42dfd9687bd592a',
    messagingSenderId: '35180612639',
    projectId: 'flutterrestapi-17c56',
    storageBucket: 'flutterrestapi-17c56.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPPhGrKUnNRz_MWRv2mzi0aw2benRTyu8',
    appId: '1:35180612639:web:435cdf9cc044ede6bd592a',
    messagingSenderId: '35180612639',
    projectId: 'flutterrestapi-17c56',
    authDomain: 'flutterrestapi-17c56.firebaseapp.com',
    storageBucket: 'flutterrestapi-17c56.appspot.com',
    measurementId: 'G-NDX92WBM8D',
  );
}
